### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by Am0rphous** [SAJAD-net/GeekWall#1]
Hey! Cool pics!

Would it be of interest to show preview of the pics on in the readme.md file?

I made a [similar type of repo](https://github.com/Am0rphous/Awesome-Wallpapers) earlier where i show some pics. It makes it nice to quickly view the pics in stead of navigating into the pic folder and viewing them one by one.

Cheers!

**Comment by SAJAD-net** [comment]
Hey!
That's a good idea!
Thanks.
